version: "2"

services:
  cicd:
    restart: unless-stopped
    # image: cloudgenius/jenkins-withdocker:lts
    build: .
    ports:
      - 80:8080
      - 443:8443
      - 50000:50000
    container_name: cicd
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    environment:
      - VIRTUAL_HOST=cicd.cloudgeni.us
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=cicd.cloudgeni.us
      - LETSENCRYPT_EMAIL=nilesh@cloudgeni.us

volumes:
  jenkins_home:
