version: "2"

services:
  cicd:
    restart: unless-stopped
    # image: cloudgenius/jenkins-withdocker:lts
    build: .
    ports:
      - 8080:8080
      - 50000:50000
    container_name: cicd
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      - ~/.kube/:/kube
    environment:
      - VIRTUAL_HOST=cicd.cloudgeni.us
      - VIRTUAL_PORT=8080
      - KUBECONFIG=/kube/config

volumes:
  jenkins_home:
