version: "2"

services:
  nginx-proxy:
    restart: unless-stopped
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    restart: unless-stopped
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  cicd:
    restart: unless-stopped
    # image: cloudgenius/jenkins-withdocker:lts
    build: .
    container_name: cicd
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      - ~/.kube/:/kube
    environment:
      - VIRTUAL_HOST=cicd.cloudgenius.app
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=cicd.cloudgenius.app
      - LETSENCRYPT_EMAIL=nilesh@cloudgeni.us
      - KUBECONFIG=/kube/config
      - GKE_SERVICE_ACCOUNT=ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAib2NlYW5pYy1pc290b3BlLTIzMzUyMiIsCiAgInByaXZhdGVfa2V5X2lkIjogImNiN2JiODllYjE3OTAyYWM0NTk2NjVmM2IwMzhmNDAxMTU3MThjNGYiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQzNsTG0rMG1QakRBaCtcbmE3ck9xV0VzT3BUY3NGcVJxMmtoZVh3Q3g1YkdlZHRwQStLYmlqUnRVUGZwbTBYZGJBQzRMMDZiamFjOUloRTVcbmdLVFdIeGJDSGM3cTljTDRsUTBsSlFGT1VKaExnZkNBTHJ1ZW9qYTk4NWMyci9kUytQcnlpU0ZMVEIxdHVVVlZcbnBFclFKbE5sV2pZbDlQVXhJamlPYVpralBtWjJqY2lNWHpTcFNuckJabWpvaFJlUGF4SjF5VHBZR1VQUTJHVk1cbmhxc3hHck5Eb1BBckhSN2hhQkRTQjNZSkpsS29aQmVYaG0vSHhUaVYveUM0MStZMURvS3Nkb00wdlpoZDNnZGFcblFlMW53ZC8rVm11S2FIMWlvRDA4QUNqd29DVWtEVDBoN1lCcm9NVS9OZVBEamovVHdYazBoRUZ6RnpUT3Fxem1cblNieWF1clZsQWdNQkFBRUNnZ0VBUmdvUWVheVVIbDRMYVl3Wlo5bzRjQ0xqZzNVbkFMZUljeFNCeXgreHR3UnJcbndOdVNHNngxUnhXaWwvWTlCL2E2S1lzbTd2THkwTUNNR01lclcrUGRqMjdHOEY2V0piZmNIWVZLUThJODhHWGhcblIwNU5GMzhrNm9DaWV1TlV0VXUzbGt2YUwzdVpLTEVNTWxudGp3OW9OdDFkbGtxb056Z3FvcTdJRmFtcmR1UUdcbllYR0s0TEx3THBMNkJRdDVQZk9JMFRjNDRDa0xqdTdrWkd3NXk5S3EwS0VZSmwxZ0wyclhNV2N2SkxlMHFBaXJcblhDL1JoQ2hFV3JPR2MyVnhKOHFWcTBVQklmSHRrT1RTRFZxNDBHVHVLbFVRcURmdTdORjdMRGxFdlNOK2o1QkhcblpoeUE0VjdaSStLSkRya3F5cTVidlIzL3pHUHVoWlEzbVdzcnk4QVcrd0tCZ1FELzZ2cW1DWWMzR29reURIZkZcbkZadnZ0WUxTTFdNYkNOeTlWTEoxaDFmbFg3UzBNeDVSVWpsb3V0YThiK1RIM1Y4VjlUTndxT0ZsSUtIQzJaejZcbmw5RkhNbkczM1dtM0VVUGlId1NLQXF5K1RjTjdHb1puYjdnSEhjVkdWNlZPNzJNMktUdG9IZTJBVVBBQURwWVZcbk0rK3RidTRVRHNXZkNyVUdWQnJMbDAvWkJ3S0JnUUMzbzg0RmRKMDcvUFZtNWhJUFIrZE5GeEVqeTM1ak9SLzBcbklTcDdqN0wxYXh2UFhSSDRFN3NBS1FXbFQ5dDNCbWovVDdlMkZZZHNQbWtTcTZlTHdOVERkaTYvY2NYejlLb0xcbjVqOGtkNm05R1NkSk1Uamh1Q2R0OVFhSDFyaWJSWjJpUXN4ZC82ekljL2RtdGp0SHQvOFJEbk83QTBwaUVpSTZcblFYN2QyNWgvTXdLQmdIR0hPelFIREEzYzNybnVILysxSzF6Mmg1ZFhmUnlVSE9COHYwSTJEVDc2NnYzNW8xeHRcbi9udkFUdHgvUXQyTERkQisyeGdDUXlNS2k5Z1ZrM2J6ZkdwNkxVcGtsYTRab2FTaEgvRmRhR1p2dHVWWWlnRStcbjVVTjY2SFhoRWJ0bnBQcDA1aDYxRUJRWlU2Nml5ZCtVRDZJL2tLd2pOWFh0V1FyNnFueGducEpuQW9HQVdoeXdcbk9POGJSTmVCR0NnbmpvWUxFMElSY0E0b0M4cDVTcE9IeERBa2NkZElRejM1VmxGZ1B0amlZMWRIYXlXakdqMWtcbitaMmc0VlhTdTQydDNwOFdDSUFTdW5DNjRWWWFwMUlwZzl5UVZ6RmpuTC9obUttRDk2bjN0V3FCRmZoWVBNb29cbmZLdThmblNoWHk1bThtOXdZMDlETE82VmJvQlZlVjZ3UVcvRGFnOENnWUIyZStpUlN0d3JZT0xoeEdjZHdFd3NcblRWQngxcUJ0ZTlnY01UaWt5TmI3cVhzcFdITWd4NkliQ05iR3Qra09YMUhPTHY1d3FPUG9rYmpNT2thUTd3bjlcbnZDK2NrOTNSd2JrMzRRek94SDhob2UwNStPaCtVWmR3L0VJbjhhN0M0amFtQnZLa1plLzI5RVRCa2o4OHQ5OXJcbnpMMGo0U0JqM0lVd3ZuUENDczU5ZFE9PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImltYWMtdG8tZ2tlLWNsdXN0ZXJAb2NlYW5pYy1pc290b3BlLTIzMzUyMi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDI2ODU0MTAyOTU1MjI0MjEwNDYiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCIasdodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ltYWMtdG8tZ2tlLWNsdXN0ZXIlNDBvY2VhbmljLWlzb3RvcGUtMjMzNTIyLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9Cg==
      - GKE_PROJECT_ID=intense-cortex-271814
      - GKE_COMPUTE_ZONE=us-west1-a
      - GKE_CLUSTER_NAME=andromeda
      - D_USER=lvnilesh
      - D_PASS=token
      - GH_PAT=token
      - AWS_ACCESS_KEY_ID=id
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_DEFAULT_REGION=us-west-2

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  jenkins_home:
